application/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Routes for Downloads and Uploads pages
  get "downloads" => "download_status#index", as: :download_status
  get "downloads/files" => "download_status#files", as: :download_status_files
  get "uploads" => "upload_status#index", as: :upload_status
  get "uploads/files" => "upload_status#files", as: :upload_status_files

  # REST routes over /projects and /projects/:id
  # post /projects/:id/set_active => set project as active
  resources :projects do
    post :set_active, on: :member

    # delete /projects/:project_id/downloads/files/:id => delete download file
    # post /projects/:project_id/downloads/files/:id/cancel => cancel download file
    # post /projects/:project_id/downloads/files/:id/retry => retry download file
    resources :download_files, path: 'downloads/files', only: [:destroy] do
      post :cancel, on: :member
      post :retry, on: :member
    end

    # post /projects/:project_id/uploads => create new upload batch
    # get /projects/:project_id/uploads => get batches from a project
    resources :upload_bundles, path: 'uploads', only: [:index, :update, :destroy] do
      # POST /projects/:project_id/uploads/connector => create new upload bundle via connector
      post :connector, on: :collection, to: 'upload_bundles_connector#create'

      # GET /projects/:project_id/uploads/:upload_bundle_id/connector/edit => edit connector form
      # PUT /projects/:project_id/uploads/:upload_bundle_id/connector => update via connector
      resource :connector, only: [:edit, :update], controller: 'upload_bundles_connector'

      # post /projects/:project_id/uploads/:upload_bundle_id/files => create new upload_file
      # get /projects/:project_id/uploads/:upload_bundle_id/files => gets upload_files from a collection
      # delete /projects/:project_id/uploads/:upload_bundle_id/files/:id => delete upload_file
      # post /projects/:project_id/uploads/:upload_bundle_id/files/:id/cancel => cancel upload_file
      # post /projects/:project_id/uploads/:upload_bundle_id/files/:id/retry => retry upload_file
      resources :upload_files, path: 'files', only: [ :create, :index, :destroy ] do
        post :cancel, on: :member
        post :retry, on: :member
      end
    end

  end

  # REPO RESOLVER ROUTES
  post '/view/repo/resolve' => 'repo_resolver#resolve', as: :repo_resolver

  # REPOSITORY SETTINGS ROUTES
  resources :repository_settings, path: 'repositories/settings', only: [:index, :create] do
    collection do
      put :update
      delete :destroy
    end
  end

  #FILE ACTIVITY
  get '/detached_process/status', to: 'detached_process#status'
  # FILE BROWSER
  get '/file_browser', to: 'file_browser#index'
  # WIDGETS
  match '/widgets/*widget_path', to: 'widgets#show', via: [:get, :post], as: 'widgets'
  # SITEMAP
  get '/sitemap' => 'sitemap#index', as: :sitemap

  # EXPLORE ROUTE
  get "/explore/:connector_type/*server_domain/:object_type/*object_id" => "explore#show", as: :explore
  post "/explore/:connector_type/*server_domain/:object_type/*object_id" => "explore#create"

  # CONNECT ROUTES
  get "/connect/:connector_type/:object_type" => "connect#show", as: :connect_repo
  post "/connect/:connector_type/:object_type" => "connect#handle"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

application/app/helpers/layout_helper.rb
# app/helpers/layout_helper.rb
module LayoutHelper
  # Returns true if we are on a given controller/action
  def on_page?(controller: nil, action: nil)
    (controller.nil? || params[:controller] == controller.to_s) &&
      (action.nil? || params[:action] == action.to_s)
  end

  def on_project_index?
    on_page?(controller: 'projects', action: 'index')
  end

  def on_explore?
    on_page?(controller: 'explore')
  end
end

application/app/views/layouts/_app_actions_bar.html.erb
<%
  url ||= repo_resolver_path
  type = on_project_index? ? 'form' : 'json'
%>
<div id="app-actions-bar" class="shadow-sm sticky-top bg-primary-subtle" style="z-index: 500;">
  <div class="d-flex align-items-center justify-content-between py-2 px-4 gap-5">
    <div class="d-flex align-items-center gap-3">
      <div class="d-flex flex-column gap-1">
        <label for="repo_resolver_project_select" class="form-label mb-0 small">
          <%= t('project_selection.selected_project_label') %>
        </label>

        <div class="d-flex align-items-center gap-2">
          <div class="dropdown flex-grow-1" data-controller="select-project" data-select-project-type-value="<%= type %>" style="width: 20rem;">
            <button class="btn btn-sm btn-outline-dark dropdown-toggle d-flex justify-content-between align-items-center text-start w-100"
                    type="button"
                    id="repo_resolver_project_dropdown"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
              <span class="flex-grow-1 text-truncate" data-select-project-target="displayLabel">
                <%= select_project_list.any? ? select_project_list.first.name : t('project_selection.button_empty_list_text') %>
              </span>
              <span class="spinner-border spinner-border-sm ms-2 d-none" data-select-project-target="spinner" role="status" aria-hidden="true"></span>
            </button>
            <ul class="dropdown-menu w-100" aria-labelledby="repo_resolver_project_dropdown">
              <% select_project_list.each do |project| %>
                <li>
                  <a href="#"
                     class="dropdown-item text-truncate"
                     title="<%= project.name %>"
                     data-action="select-project#chooseProject"
                     data-project-id="<%= project.id %>"
                     data-project-name="<%= project.name %>"
                     data-project-path="<%= project_path(project.id) %>">
                    <%= project.name %>
                  </a>
                </li>
              <% end %>
            </ul>
          </div>

          <%= link_to projects_path,
                      class: 'btn btn-sm btn-outline-dark flex-shrink-0',
                      title: t('project_selection.button_open_project_title'),
                      data: { controller: 'select-project-listener', select_project_listener_target: 'link' } do %>
            <i class="bi bi-display" aria-hidden="true"></i>
            <span class="visually-hidden"><%= t('project_selection.button_open_project_label') %></span>
          <% end %>

          <%= render layout: "shared/button_to", locals: {
            url: projects_path,
            class: 'btn btn-sm btn-outline-dark',
            title: t('project_selection.button_create_project_title'),
            icon: "bi bi-plus-square-fill",
            button_id: "app-bar-create-project-btn"
          } do %>
            <%= hidden_field_tag :redirect_back, true if on_explore? %>
          <% end %>

        </div>
      </div>

    </div>

    <div class="d-flex align-items-center flex-grow-1 gap-2">
    <%= render layout: "shared/button_to", locals: {
      url: url,
      button_id: 'explore-repo-url-submit',
      form_class: 'explore-repo d-flex align-items-center gap-2 flex-grow-1',
      class: 'btn-primary-dark',
      icon_html: image_tag('icon.png', alt: t('.button_submit_icon_alt'), class: 'icon-class d-block', style: 'height: 1rem; width: auto; object-fit: contain;' ),
      label: t('.button_submit_text')
    } do %>

      <div class="input-group">
        <span class="input-group-text bg-white">
          <%=  image_tag('doi.svg', alt: 'DOI', class: 'me-1', height: '20') %>
          <%=  image_tag('dataverse.svg', alt: 'Dataverse', class: 'me-1', height: '16') %>
          <%=  image_tag('zenodo.svg', alt: 'Zenodo', class: 'me-1', height: '16') %>
        </span>
        <input type="text"
               name="repo_url"
               id="explore-repo-url-input"
               class="form-control"
               placeholder="<%= t('layouts.app_actions_bar.input_repo_url_placeholder') %>"
               aria-label="<%= t('layouts.app_actions_bar.input_repo_url_label') %>">
      </div>
    <% end %>

    <button type="button"
            class="btn btn-primary-dark"
            title="<%= t('widgets.repository_activity.button_open_modal_title') %>"
            data-controller="modal"
            data-action="click->modal#load"
            data-modal-url-value="<%= widgets_path('repository_activity') %>"
            data-modal-title-value="<%= t('widgets.repository_activity.modal_title') %>"
            data-modal-id-value="global-modal">
      <i class="bi bi-folder-symlink-fill" style="font-size: 1.1rem;"></i>
      <span class="visually-hidden"><%= t('widgets.repository_activity.button_open_modal_title') %></span>
    </button>
    </div>

  </div>
</div>

application/app/views/layouts/_config.html.erb
<script nonce="<%= content_security_policy_nonce %>">
  window.loop_app_config = {
      csrf_token: "<%= form_authenticity_token %>",
      downloads_files_path: "<%= download_status_files_path %>",
      uploads_files_path: "<%= upload_status_files_path %>",
      connector_status_poll_interval: <%= Configuration.connector_status_poll_interval.to_i%>,
      ui_feedback_delay: <%= Configuration.ui_feedback_delay.to_i%>,
      file_drop_target_id: null,
      i18n: <%= I18n.t('js').to_json.html_safe %>
  }
</script>

application/app/views/layouts/_flash_messages.html.erb
<div id="flash-container" class="position-relative z-3">
  <% flash_messages.each do |type, message| %>
    <div class="alert-dismissible fade show <%= alert_class(type) %>" role="alert">
      <%= message.html_safe %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="<%= t('.button_close_label') %>"></button>
    </div>
  <% end %>
</div>

application/app/views/layouts/_footer.html.erb
<footer class="d-flex m-0 mt-4 justify-content-between align-items-center p-4">
  <div id="footer-iqss" class="me-2">
    <%= link_to "https://www.iq.harvard.edu/research-computing" do %>
      <%=
        image_tag(
          "iqss_logo.png",
          class: "footer-logo",
          alt: "IQSS Reserch Computing",
          height: "40",
        )
      %>
    <% end %>
  </div>

  <div id="footer-ood" class="d-flex flex-column align-items-center text-muted">

    <%=
      image_tag(
        "ood_logo.svg",
        class: "footer-logo",
        alt: "Open OnDemand Logo",
        height: "40",
        )
    %>
    <span><%= server_hostname %>: <%= ::Configuration.ood_version %></span>
  </div>

  <div id="footer-version" class="d-flex flex-column align-items-center text-muted">
    <span><%= t('.version_text') %></span>
    <span><%= ::Configuration.version %></span>
  </div>
</footer>

application/app/views/layouts/_modal.html.erb
<%
  modal_classes = local_assigns.fetch(:class, 'modal-xl')
%>
<div id="global-modal" class="modal fade" tabindex="-1" aria-hidden="true" data-controller="modal" aria-modal="true" role="dialog">
  <div class="modal-dialog <%= modal_classes %>">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title mb-0" data-modal-target="title"><%= t('.header_loading_text') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<%= t('.button_close_label') %>"></button>
      </div>

      <div class="modal-body p-4 position-relative">
        <div class="modal-overlay d-none" data-modal-target="spinner">
          <div class="spinner-border text-primary" role="status" aria-live="polite"></div>
        </div>

        <div data-modal-target="content"></div>
      </div>

    </div>
  </div>
</div>

application/app/views/layouts/_modal_delete_confirmation.html.erb
<div id="modal-delete-confirmation"
     class="modal fade"
     tabindex="-1"
     role="dialog"
     aria-modal="true"
     aria-live="assertive"
     aria-labelledby="modal-confirm-title"
     aria-describedby="modal-confirm-description"
     data-controller="modal">

  <div class="modal-dialog w-50">
    <div class="modal-content overflow-hidden">

      <div class="modal-header pb-2">
        <div class="d-flex flex-column">
          <h5 id="modal-confirm-title" class="modal-title mb-0">
            <i class="bi bi-question-circle-fill text-primary me-1" aria-hidden="true"></i>
            <span data-modal-target="title"><%= t('.header_title') %></span>
          </h5>
          <small class="text-muted" data-modal-target="subtitle" style="margin-top: -3px;"><%= t('.subtitle_default_text') %></small>
        </div>
        <button type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="<%= t('.button_close_label') %>"></button>
      </div>

      <div class="modal-body p-4 position-relative">
        <!-- Confirmation message -->
        <div>
          <p id="modal-confirm-description" class="mb-4 text-body" data-modal-target="content">
            <%= t('.content_text') %>
          </p>

          <div class="d-flex justify-content-center gap-4">
            <button type="submit" class="btn btn-danger w-25" data-action="modal#confirm">
              <i class="bi bi-trash me-1" aria-hidden="true"></i>
              <span data-modal-target="confirmText"><%= t('.button_confirm_text') %></span>
            </button>
            <button type="button" class="btn btn-secondary w-25" data-bs-dismiss="modal">
              <%= t('.button_cancel_text') %>
            </button>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

application/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg shadow-sm bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= render partial: 'layouts/nav/logo' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= nav_link_to "Downloads", downloads_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= nav_link_to "DOI Search", doi_search_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Repositories
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="<%= view_dataverse_landing_path %>">Dataverse</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto"> <!-- ms-auto pushes this section to the right -->
        <li class="nav-item">
          <%= nav_link_to "Restart", restart_url, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

application/app/views/layouts/_project_bar.html.erb
<div class="border-bottom py-2 px-5 d-flex justify-content-between align-items-center shadow-sm <%= project_header_class(true) %>">
  <div class="d-flex align-items-center gap-3">
    <a href="<%= files_app_url(project.download_dir) %>"
       target="_blank"
       class="btn btn-sm btn-outline-secondary"
       title="<%= t('.link_open_downloads_title') %>">
      <i class="bi bi-folder-fill" aria-hidden="true"></i>
      <span class="visually-hidden"><%= t('.link_open_downloads_title') %></span>
    </a>

    <%= render partial: '/shared/file_row_date', locals: { date: project.creation_date, title: t('.field_creation_date_title')} if project.creation_date %>

    <!-- PROJECT METADATA -->
    <div class="d-flex flex-column">
      <%= link_to project_path(id: project.id), class: "position-relative project-name-link text-reset text-decoration-none rounded-end ps-1 pe-3" do %>
        <h2 class="mb-0 h5"><%= project.name %></h2>
        <small class="text-muted"><%= project.download_dir %></small>
      <% end %>
    </div>
  </div>

  <div>
    <%= render partial: '/shared/metadata_folder_link',
               locals: { path: Project.project_metadata_dir(project.id),
                         class: 'btn btn-sm btn-outline-primary ms-3' } %>
    <button class="btn btn-sm btn-outline-primary cursor-default" title="<%= t('.button_active_project_title') %>" type="button">
      <i class="bi bi-check-circle-fill" aria-hidden="true"></i>
      <span class="visually-hidden"><%= t('.button_active_project_title') %></span>
    </button>
  </div>
</div>

application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>">
  <head>
    <title><%= content_for(:title) || "OnDemand Loop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="<%= asset_path "icon.png" %>" type="image/png">
    <link rel="apple-touch-icon" href="<%= asset_path "icon.png" %>">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>

    <%= render partial: '/layouts/config' %>
  </head>

  <body>
    <%= render partial: '/layouts/nav/nav',  locals: { navigation: ::Configuration.navigation } %>
    <%= render partial: '/layouts/app_actions_bar' %>
    <h1 class="visually-hidden"><%= content_for(:title) || 'OnDemand Loop' %></h1>
    <div id="main_container" class="container-md content mt-4" role="main">
      <%= render partial: '/layouts/flash_messages' %>
      <%= yield %>
    </div>


    <%= render partial: "/layouts/footer" %>

    <%= render partial: '/layouts/modal' %>
    <%= render partial: '/layouts/modal_delete_confirmation' %>
  </body>
</html>